- name: Deploy database
  hosts: backend
  become: true
  vars_files:
    - ./vars/project.yml
  tasks:
    - name: copy project
      copy:
        src: "{{project_dir}}"
        dest: /project

    - name: Install Docker Module for Python
      pip:
        name: docker

    - pip:
        name: docker_compose

    - docker_compose:
        build: true
        services:
          - database
        project_src: /project/infrastructure
