- name: Install nginx
  hosts: all
  tasks:
    - name: Install nginx on Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" and
        ansible_distribution_version == "16.04"

    - name: Install nginx on CentOS
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat" or
        ansible_os_family == "Suse"
