- name: Line in file module
  hosts: all
  become: true
  vars:
    message: have a nice day
  tasks:
    - name: touch file
      command: touch /etc/test2.txt

    - lineinfile:
        path: /etc/test2.txt
        line: "message is: {{message}}"

    # - name: "by script"
    #   command: echo 'success' >> /etc/test2.txt
