- name: Using async
  hosts: controllers
  tasks:
    - name: Async module
      block:
        - name: Sleep
          command: /bin/sleep 15
          async: 100
          poll: 0
          register: sleep
        - debug:
            var: sleep
        - name: Echo
          command: echo "DONE"
      become: yes
    - name: Check sleep status
      async_status:
        jid: "{{ sleep.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 1
      become: true
